version: "3"
services:
  full-stack-ml:
    container_name: full-stack-ml
    image: louisdorard/full-stack-ml:2020-02-24-workshop
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - "9999:9999"
      - "6006:6006"
    volumes:
      - ../../:/home/devel/full-stack-ml
      - ${DATA_PATH}:/data
    environment: 
        - DATA_PATH=/data/
    env_file: 
        - ~/auth.env
    command: /opt/conda/envs/full-stack-ml/bin/jupyter lab --ip='0.0.0.0' --port=9999 --no-browser --allow-root
